export const CodigosEstadoSolicitud = {
  REGISTRADA: 'REGISTRADA',
  EN_ANALISIS: 'EN_ANALISIS',
  EN_PROGRESO: 'EN_PROGRESO',
  EN_ESPERA_SOLICITANTE: 'EN_ESPERA_SOLICITANTE',
  RESUELTA: 'RESUELTA',
  CERRADA: 'CERRADA',
} as const;
