// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SB.PortalSolicitudes.Infraestructure.Persistence;

#nullable disable

namespace SB.PortalSolicitudes.Infraestructure.Persistence.Migrations
{
    [DbContext(typeof(PortalSolicitudesDbContext))]
    [Migration("20260910043656_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.Adjunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Adjuntos", (string)null);
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Areas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Tecnología de la Información"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Supervisión Bancaria"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "Administración y Finanzas"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "Consultoría Jurídica"
                        });
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsInterno")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("SolicitudId", "EsInterno");

                    b.ToTable("Comentarios", (string)null);
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.EstadoSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("EsFinal")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Orden")
                        .IsUnique();

                    b.ToTable("EstadosSolicitud", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Codigo = "REGISTRADA",
                            EsFinal = false,
                            Nombre = "Registrada",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Codigo = "EN_ANALISIS",
                            EsFinal = false,
                            Nombre = "En análisis",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Codigo = "EN_PROGRESO",
                            EsFinal = false,
                            Nombre = "En progreso",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Codigo = "EN_ESPERA_SOLICITANTE",
                            EsFinal = false,
                            Nombre = "En espera del solicitante",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Codigo = "RESUELTA",
                            EsFinal = false,
                            Nombre = "Resuelta",
                            Orden = 5
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Codigo = "CERRADA",
                            EsFinal = true,
                            Nombre = "Cerrada",
                            Orden = 6
                        });
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.HistorialEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("EstadoAnteriorId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoAnteriorId");

                    b.HasIndex("EstadoNuevoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("SolicitudId", "EstadoNuevoId");

                    b.ToTable("HistorialEstados", (string)null);
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Canal")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioDestinoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("UsuarioDestinoId");

                    b.ToTable("Notificaciones", (string)null);
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.Prioridad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nivel")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Prioridades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nivel = 1,
                            Nombre = "Baja"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nivel = 2,
                            Nombre = "Media"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nivel = 3,
                            Nombre = "Alta"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nivel = 4,
                            Nombre = "Crítica"
                        });
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCompromiso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadId")
                        .HasColumnType("int");

                    b.Property<int>("TipoSolicitudId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("UsuarioAsignadoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioSolicitanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EstadoId");

                    b.HasIndex("FechaCompromiso");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("PrioridadId");

                    b.HasIndex("TipoSolicitudId");

                    b.HasIndex("UsuarioAsignadoId");

                    b.HasIndex("UsuarioSolicitanteId");

                    b.ToTable("Solicitudes", (string)null);
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.TipoSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposSolicitud", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Fallas de equipos, red o servicios de tecnología.",
                            Nombre = "Soporte técnico"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Altas, bajas y cambios de permisos en aplicaciones internas.",
                            Nombre = "Acceso a sistemas"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Solicitud, reemplazo o traslado de equipos.",
                            Nombre = "Equipo y hardware"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Instalaciones, licencias y nuevas funcionalidades.",
                            Nombre = "Requerimiento de software"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Dudas y orientación que no encajan en otro tipo.",
                            Nombre = "Consulta general"
                        });
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.TransicionPermitida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("EstadoDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoOrigenId")
                        .HasColumnType("int");

                    b.Property<bool>("RequiereComentario")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EstadoDestinoId");

                    b.HasIndex("EstadoOrigenId", "EstadoDestinoId")
                        .IsUnique();

                    b.ToTable("TransicionesPermitidas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            EstadoDestinoId = 2,
                            EstadoOrigenId = 1,
                            RequiereComentario = false
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            EstadoDestinoId = 3,
                            EstadoOrigenId = 2,
                            RequiereComentario = false
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            EstadoDestinoId = 4,
                            EstadoOrigenId = 3,
                            RequiereComentario = true
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            EstadoDestinoId = 3,
                            EstadoOrigenId = 4,
                            RequiereComentario = false
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            EstadoDestinoId = 5,
                            EstadoOrigenId = 3,
                            RequiereComentario = true
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            EstadoDestinoId = 3,
                            EstadoOrigenId = 5,
                            RequiereComentario = true
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            EstadoDestinoId = 6,
                            EstadoOrigenId = 5,
                            RequiereComentario = false
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            EstadoDestinoId = 2,
                            EstadoOrigenId = 6,
                            RequiereComentario = true
                        });
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.TransicionPermitidaRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<int>("TransicionPermitidaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransicionPermitidaId", "Rol")
                        .IsUnique();

                    b.ToTable("TransicionesPermitidasRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Rol = 1,
                            TransicionPermitidaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Rol = 2,
                            TransicionPermitidaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Rol = 1,
                            TransicionPermitidaId = 2
                        },
                        new
                        {
                            Id = 4,
                            Rol = 2,
                            TransicionPermitidaId = 2
                        },
                        new
                        {
                            Id = 5,
                            Rol = 1,
                            TransicionPermitidaId = 3
                        },
                        new
                        {
                            Id = 6,
                            Rol = 2,
                            TransicionPermitidaId = 3
                        },
                        new
                        {
                            Id = 7,
                            Rol = 1,
                            TransicionPermitidaId = 4
                        },
                        new
                        {
                            Id = 8,
                            Rol = 2,
                            TransicionPermitidaId = 4
                        },
                        new
                        {
                            Id = 9,
                            Rol = 3,
                            TransicionPermitidaId = 4
                        },
                        new
                        {
                            Id = 10,
                            Rol = 1,
                            TransicionPermitidaId = 5
                        },
                        new
                        {
                            Id = 11,
                            Rol = 2,
                            TransicionPermitidaId = 5
                        },
                        new
                        {
                            Id = 12,
                            Rol = 1,
                            TransicionPermitidaId = 6
                        },
                        new
                        {
                            Id = 13,
                            Rol = 2,
                            TransicionPermitidaId = 6
                        },
                        new
                        {
                            Id = 14,
                            Rol = 1,
                            TransicionPermitidaId = 7
                        },
                        new
                        {
                            Id = 15,
                            Rol = 2,
                            TransicionPermitidaId = 7
                        },
                        new
                        {
                            Id = 16,
                            Rol = 3,
                            TransicionPermitidaId = 7
                        },
                        new
                        {
                            Id = 17,
                            Rol = 1,
                            TransicionPermitidaId = 8
                        },
                        new
                        {
                            Id = 18,
                            Rol = 2,
                            TransicionPermitidaId = 8
                        });
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.Adjunto", b =>
                {
                    b.HasOne("SB.PortalSolicitudes.Domain.Entities.Solicitud", "Solicitud")
                        .WithMany("Adjuntos")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SB.PortalSolicitudes.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.Comentario", b =>
                {
                    b.HasOne("SB.PortalSolicitudes.Domain.Entities.Solicitud", "Solicitud")
                        .WithMany("Comentarios")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SB.PortalSolicitudes.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.HistorialEstado", b =>
                {
                    b.HasOne("SB.PortalSolicitudes.Domain.Entities.EstadoSolicitud", "EstadoAnterior")
                        .WithMany()
                        .HasForeignKey("EstadoAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SB.PortalSolicitudes.Domain.Entities.EstadoSolicitud", "EstadoNuevo")
                        .WithMany()
                        .HasForeignKey("EstadoNuevoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SB.PortalSolicitudes.Domain.Entities.Solicitud", "Solicitud")
                        .WithMany("Historial")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SB.PortalSolicitudes.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoAnterior");

                    b.Navigation("EstadoNuevo");

                    b.Navigation("Solicitud");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("SB.PortalSolicitudes.Domain.Entities.Solicitud", "Solicitud")
                        .WithMany("Notificaciones")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SB.PortalSolicitudes.Domain.Entities.Usuario", "UsuarioDestino")
                        .WithMany()
                        .HasForeignKey("UsuarioDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("UsuarioDestino");
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.Solicitud", b =>
                {
                    b.HasOne("SB.PortalSolicitudes.Domain.Entities.Area", "Area")
                        .WithMany("Solicitudes")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SB.PortalSolicitudes.Domain.Entities.EstadoSolicitud", "Estado")
                        .WithMany("Solicitudes")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SB.PortalSolicitudes.Domain.Entities.Prioridad", "Prioridad")
                        .WithMany("Solicitudes")
                        .HasForeignKey("PrioridadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SB.PortalSolicitudes.Domain.Entities.TipoSolicitud", "TipoSolicitud")
                        .WithMany("Solicitudes")
                        .HasForeignKey("TipoSolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SB.PortalSolicitudes.Domain.Entities.Usuario", "UsuarioAsignado")
                        .WithMany("SolicitudesAsignadas")
                        .HasForeignKey("UsuarioAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SB.PortalSolicitudes.Domain.Entities.Usuario", "UsuarioSolicitante")
                        .WithMany("SolicitudesSolicitadas")
                        .HasForeignKey("UsuarioSolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Estado");

                    b.Navigation("Prioridad");

                    b.Navigation("TipoSolicitud");

                    b.Navigation("UsuarioAsignado");

                    b.Navigation("UsuarioSolicitante");
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.TransicionPermitida", b =>
                {
                    b.HasOne("SB.PortalSolicitudes.Domain.Entities.EstadoSolicitud", "EstadoDestino")
                        .WithMany("TransicionesDeEntrada")
                        .HasForeignKey("EstadoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SB.PortalSolicitudes.Domain.Entities.EstadoSolicitud", "EstadoOrigen")
                        .WithMany("TransicionesDeSalida")
                        .HasForeignKey("EstadoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoDestino");

                    b.Navigation("EstadoOrigen");
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.TransicionPermitidaRol", b =>
                {
                    b.HasOne("SB.PortalSolicitudes.Domain.Entities.TransicionPermitida", "TransicionPermitida")
                        .WithMany("RolesPermitidos")
                        .HasForeignKey("TransicionPermitidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransicionPermitida");
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.Area", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.EstadoSolicitud", b =>
                {
                    b.Navigation("Solicitudes");

                    b.Navigation("TransicionesDeEntrada");

                    b.Navigation("TransicionesDeSalida");
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.Prioridad", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.Solicitud", b =>
                {
                    b.Navigation("Adjuntos");

                    b.Navigation("Comentarios");

                    b.Navigation("Historial");

                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.TipoSolicitud", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.TransicionPermitida", b =>
                {
                    b.Navigation("RolesPermitidos");
                });

            modelBuilder.Entity("SB.PortalSolicitudes.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("SolicitudesAsignadas");

                    b.Navigation("SolicitudesSolicitadas");
                });
#pragma warning restore 612, 618
        }
    }
}
